---
version: '2.4'
services:
  mongodb:
    image: mongo:4.1
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb

  parity:
    image: parity/parity:v2.4.6
    command: --config /app/parity_config.toml
    working_dir: /app
    user: root
    restart: unless-stopped
    ports:
      - '30303:30303/tcp'
      - '30303:30303/udp'
    volumes:
      - ./chain.json:/app/chain.json
      - ./parity_config.toml:/app/parity_config.toml
      - ./chains:/app/chains

  worker: &hermes-props
    image: ambrosus/ambrosus-node:<ENTER_DOCKER_TAG_HERE>
    command: sh -c 'yarn migrate && yarn start:hermes'
    restart: unless-stopped
    depends_on:
      - mongodb
      - parity
    environment:
      - WEB3_NODEPRIVATEKEY=<ENTER_YOUR_PRIVATE_KEY_HERE>
      - HEAD_CONTRACT_ADDRESS=<ENTER_YOUR_HEAD_CONTRACT_ADDRESS_HERE>
      - WEB3_RPC=http://parity:8545
      - MONGO_HOSTS=mongodb:27017
      - MONGO_DB_NAME=ambrosus
      - AUTHORIZATION_WITH_SECRET_KEY_ENABLED=false
      - NODE_ENV=production

  server:
    <<: *hermes-props
    command: sh -c 'yarn start:server'
    depends_on:
      - worker
    ports:
      - 80:9876
