[parity]
base_path = "/app/"
chain = "/app/chain.json"

[network]
warp = false

[rpc]
apis = ["web3", "eth", "net"]
interface = "all"
cors = ["*"]

[websockets]
apis = ["web3", "eth", "net"]
interface = "all"

[ipc]
disable = true

[misc]
logging = "own_tx=trace"
