---
version: '2.4'
services:
  mongodb:
    image: mongo:4.1
    restart: unless-stopped

  parity:
    image: parity/parity:v2.1.1
    command: --config /app/parity_config.toml
    working_dir: /app
    restart: unless-stopped
    entrypoint: /entrypoint.sh
    ports:
      - '30303:30303/tcp'
      - '30303:30303/udp'
    volumes:
      - ../../chain.json:/app/chain.json
      - ./parity_config.toml:/app/parity_config.toml

  server: &atlas-props
    image: ambrosus/ambrosus-node:latest
    command: bash -c 'yarn migrate && yarn start:server'
    restart: unless-stopped
    depends_on:
      - mongodb
      - parity
    ports:
      - 9876:9876
    environment:
      - WEB3_NODEPRIVATEKEY=0x44f09b0e090e4008cc3175970addfe2cebb2c64a314bd0d7b1af27d61a9972a5
      - WEB3_RPC=http://parity:8545
      - HEAD_CONTRACT_ADDRESS=0x0000000000000000000000000000000000000f10
      - MONGO_HOSTS=mongodb:27017
      - MONGO_DB_NAME=ambrosus
      - AUTHORIZATION_WITH_SECRET_KEY_ENABLED=false
      - NODE_ENV=production

  worker:
    <<: *atlas-props
    command: bash -c 'yarn migrate && yarn start:atlas'
