---
version: '2.4'
services:
  parity:
    image: parity/parity:v2.0.8
    entrypoint: /home/parity/bin/parity
    command: --config /mnt/parity/config.toml
    working_dir: /mnt/parity
    user: root
    restart: unless-stopped
    ports:
      - '30303:30303/tcp'
      - '30303:30303/udp'
    volumes:
      - ./chain.json:/app/chain.json
      - ./password.pwds:/app/password.pwds
      - ./parity_config.toml:/app/config.toml
      - ./keyfile:/app/keys/<ENTER_NETWORK_NAME_HERE>/keyfile 
