---
version: '2.4'
services:
  parity:
    image: ambrosus/parity:v2.2.10
    container_name: parity
    command: --config /app/parity_config.toml
    working_dir: /app
    user: root
    restart: unless-stopped
    ports:
      - '127.0.0.1:8545:8545/tcp'
      - '30303:30303/tcp'
      - '30303:30303/udp'
    volumes:
      - ./chain.json:/app/chain.json
      - ./password.pwds:/app/password.pwds
      - ./parity_config.toml:/app/parity_config.toml
      - ./keyfile:/app/keys/<ENTER_NETWORK_NAME_HERE>/keyfile
      - ./chains:/app/chains
