---
version: '2.4'
services:
  parity:
    image: parity/parity:v2.5.13-stable
    container_name: parity
    command: --config /app/parity_config.toml
    working_dir: /app
    user: root
    restart: unless-stopped
    ports:
      - '127.0.0.1:8545:8545/tcp'
      - '30303:30303/tcp'
      - '30303:30303/udp'
    volumes:
      - ./chain.json:/app/chain.json
      - ./password.pwds:/app/password.pwds
      - ./parity_config.toml:/app/parity_config.toml
      - ./keyfile:/app/keys/<ENTER_NETWORK_NAME_HERE>/keyfile
      - ./chains:/app/chains

  ethstats-client:
    image: quay.io/ambrosus/ethstats-client
    container_name: ethstats_client
    restart: unless-stopped
    logging:
      options:
        max-size: '100m'
        max-file: '3'
    depends_on:
      - parity
    environment:
      RPC_HOST: parity
      WS_SERVER: wss://stats.<ENTER_DOMAIN_HERE>
      WS_SECRET: Z2hTiWBUfTNc5o9BAm
      INSTANCE_NAME: 'apollo <ENTER_YOUR_ADDRESS_HERE>'
