---
version: '2.4'
services:
  parity:
    image: parity/parity:v2.1.1
    command: --config /app/config.toml
    working_dir: /app
    restart: unless-stopped
    entrypoint: /entrypoint.sh
    ports:
      - '30303:30303/tcp'
      - '30303:30303/udp'
    volumes:
      - ../../chain.json:/app/chain.json
      - ./password.pwds:/app/password.pwds
      - ./network_key:/app/network/key
      - ./parity_config.toml:/app/config.toml
      - ./keyfile:/app/keys/ambnet-dev/
