[parity]
base_path = "/app/"
chain = "/app/chain.json"

[rpc]
apis = ["web3", "eth", "net", "parity"]
interface = "all"

[ui]
disable = true

[account]
password = ["/app/password.pwds"]

[mining]
engine_signer = "<TYPE_YOUR_ADDRESS_HERE>"
reseal_on_txs = "none"
force_sealing = true

[misc]
logging = "own_tx=trace"
